/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.moonlight.moonlightapp.views.materiaprimas;

import com.moonlight.moonlightapp.daos.MateriaPrimaDAO;
import com.moonlight.moonlightapp.models.MateriaPrimaModel;
import com.moonlight.moonlightapp.services.materiasprimas.BuscarMateriaPrimaService;
import com.moonlight.moonlightapp.services.materiasprimas.DeletarMateriaPrimaService;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class RemoverMateriaPrimaView extends javax.swing.JFrame {
    private final BuscarMateriaPrimaService buscarMateriaPrimaService;
    private final DeletarMateriaPrimaService deletarMateriaPrimaService;

    public RemoverMateriaPrimaView() {
        initComponents();
        buscarMateriaPrimaService = new BuscarMateriaPrimaService();
        deletarMateriaPrimaService = new DeletarMateriaPrimaService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbRemoverMateriaPrima = new javax.swing.JComboBox<>();
        btnConfirmarRemocao = new javax.swing.JButton();
        btnCancelarRemocao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remover Matéria-Prima");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Remover Matéria Prima");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Selecione a Matéria Prima");

        cbRemoverMateriaPrima.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbRemoverMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRemoverMateriaPrimaActionPerformed(evt);
            }
        });

        btnConfirmarRemocao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirmarRemocao.setText("Confirmar");
        btnConfirmarRemocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRemocaoActionPerformed(evt);
            }
        });

        btnCancelarRemocao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarRemocao.setText("Cancelar");
        btnCancelarRemocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRemocaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                        .createSequentialGroup()
                                                        .addComponent(btnConfirmarRemocao)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnCancelarRemocao))
                                                .addComponent(cbRemoverMateriaPrima,
                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 325,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(104, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbRemoverMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnConfirmarRemocao)
                                        .addComponent(btnCancelarRemocao))
                                .addGap(72, 72, 72)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        cbRemoverMateriaPrima.removeAllItems();

        buscarMateriaPrimaService.buscarTodos().forEach(m -> {
            cbRemoverMateriaPrima.addItem(m);
        });
    }// GEN-LAST:event_formWindowOpened

    private void cbRemoverMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbRemoverMateriaPrimaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbRemoverMateriaPrimaActionPerformed

    private void btnConfirmarRemocaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConfirmarRemocaoActionPerformed
        String[] opcoes = { "NÃO", "SIM" };

        var selecao = JOptionPane.showOptionDialog(null, "Deseja confirmar a remoção da Matéria Prima?", "Confirmar",
                0, 3, null, opcoes, opcoes[0]);

        if (selecao == 1) {
            var matPrimaSelecionada = (MateriaPrimaModel) cbRemoverMateriaPrima.getSelectedItem();

            if (matPrimaSelecionada == null) {
                JOptionPane.showMessageDialog(null, "Selecione uma Matéria Prima");
            }

            var resultado = deletarMateriaPrimaService.deletar(matPrimaSelecionada.getNome());

            JOptionPane.showMessageDialog(null, resultado.getMensagem());
            dispose();
        }

        else {
            JOptionPane.showMessageDialog(null, "Remoção Cancelada");
        }

    }// GEN-LAST:event_btnConfirmarRemocaoActionPerformed

    private void btnCancelarRemocaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarRemocaoActionPerformed
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:
    }// GEN-LAST:event_btnCancelarRemocaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverMateriaPrimaView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverMateriaPrimaView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverMateriaPrimaView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverMateriaPrimaView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverMateriaPrimaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRemocao;
    private javax.swing.JButton btnConfirmarRemocao;
    private javax.swing.JComboBox<MateriaPrimaModel> cbRemoverMateriaPrima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
