/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.moonlight.moonlightapp.views.processos;

import javax.swing.JOptionPane;

import com.moonlight.moonlightapp.dtos.processos.AtualizarProcessoDTO;
import com.moonlight.moonlightapp.models.ProcessoModel;
import com.moonlight.moonlightapp.services.processos.AtualizarProcessoService;
import com.moonlight.moonlightapp.services.processos.BuscarProcessoService;

/**
 *
 * @author victor.santos8
 */
public class AtualizarProcessoView extends javax.swing.JFrame {
    private final BuscarProcessoService buscarProcessoService;
    private final AtualizarProcessoService atualizarProcessoService;

    /**
     * Creates new form AtualizarProcessoView
     */
    public AtualizarProcessoView() {
        buscarProcessoService = new BuscarProcessoService();
        atualizarProcessoService = new AtualizarProcessoService();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbProcessos = new javax.swing.JComboBox<>();
        lblAtualizarProcesso = new javax.swing.JLabel();
        lblSelecioneProcesso = new javax.swing.JLabel();
        txtEtapa = new javax.swing.JTextField();
        txtCusto = new javax.swing.JTextField();
        lblEtapa = new javax.swing.JLabel();
        lblCusto = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar Processo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cbProcessos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbProcessos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProcessosItemStateChanged(evt);
            }
        });

        lblAtualizarProcesso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAtualizarProcesso.setText("Atualizar Processo");

        lblSelecioneProcesso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSelecioneProcesso.setText("Selecione o Processo");

        txtEtapa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtCusto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblEtapa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEtapa.setText("etapa");

        lblCusto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCusto.setText("custo");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAtualizarProcesso)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelecioneProcesso)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnVoltar)))
                        .addContainerGap(435, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbProcessos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEtapa)
                                    .addComponent(lblCusto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEtapa, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(txtCusto))))
                        .addGap(340, 340, 340))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAtualizarProcesso)
                .addGap(14, 14, 14)
                .addComponent(lblSelecioneProcesso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEtapa))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCusto)
                    .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnVoltar))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVoltarActionPerformed
        setVisible(false);
        dispose();
    }// GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
        var processoSelecionado = (ProcessoModel) cbProcessos.getSelectedItem();
        var etapa = txtEtapa.getText();
        var custo = 0d;
        
        try {
            custo = Double.parseDouble(txtCusto.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "custo inválido");
        }

        var dto = new AtualizarProcessoDTO(processoSelecionado.getEtapa(), etapa, custo);
        var resultado = atualizarProcessoService.atualizar(dto);

        JOptionPane.showMessageDialog(null, resultado.getMensagem());
    }// GEN-LAST:event_btnSalvarActionPerformed

    private void cbProcessosItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbProcessosItemStateChanged
        var processoSelecionado = (ProcessoModel) cbProcessos.getSelectedItem();

        txtEtapa.setText(processoSelecionado.getEtapa());
        txtCusto.setText(String.valueOf(processoSelecionado.getCusto()));
    }// GEN-LAST:event_cbProcessosItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        buscarProcessoService.buscarTodos().forEach(p -> {
            cbProcessos.addItem(p);
        });
    }// GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarProcessoView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarProcessoView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarProcessoView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarProcessoView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarProcessoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<ProcessoModel> cbProcessos;
    private javax.swing.JLabel lblAtualizarProcesso;
    private javax.swing.JLabel lblCusto;
    private javax.swing.JLabel lblEtapa;
    private javax.swing.JLabel lblSelecioneProcesso;
    private javax.swing.JTextField txtCusto;
    private javax.swing.JTextField txtEtapa;
    // End of variables declaration//GEN-END:variables
}
