/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.moonlight.moonlightapp.views.produtos;

import com.moonlight.moonlightapp.views.relatorios.RelatorioView;

/**
 *
 * @author victor.santos8
 */
public class ProdutoPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoPrincipalView
     */
    public ProdutoPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAbrirMenuVisualizarProduto = new javax.swing.JButton();
        btnAbrirMenuCadastrarProduto = new javax.swing.JButton();
        btnAbrirMenuDeletarProduto = new javax.swing.JButton();
        btnAbrirMenuAtualizarProduto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRelatorio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal Produto");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Produtos");

        btnAbrirMenuVisualizarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAbrirMenuVisualizarProduto.setText("Visualizar");
        btnAbrirMenuVisualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirMenuVisualizarProdutoActionPerformed(evt);
            }
        });

        btnAbrirMenuCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAbrirMenuCadastrarProduto.setText("Cadastrar");
        btnAbrirMenuCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirMenuCadastrarProdutoActionPerformed(evt);
            }
        });

        btnAbrirMenuDeletarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAbrirMenuDeletarProduto.setText("Deletar");
        btnAbrirMenuDeletarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirMenuDeletarProdutoActionPerformed(evt);
            }
        });

        btnAbrirMenuAtualizarProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAbrirMenuAtualizarProduto.setText("Atualizar");
        btnAbrirMenuAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirMenuAtualizarProdutoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Selecione o que deseja fazer");

        btnRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAbrirMenuVisualizarProduto)
                            .addComponent(btnAbrirMenuAtualizarProduto))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAbrirMenuCadastrarProduto)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRelatorio)
                                    .addComponent(btnAbrirMenuDeletarProduto)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrirMenuVisualizarProduto)
                    .addComponent(btnAbrirMenuCadastrarProduto))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrirMenuAtualizarProduto)
                    .addComponent(btnAbrirMenuDeletarProduto))
                .addGap(59, 59, 59)
                .addComponent(btnRelatorio)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirMenuCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirMenuCadastrarProdutoActionPerformed
        CriarProdutoView view = new CriarProdutoView();
        view.setVisible(true);
    }//GEN-LAST:event_btnAbrirMenuCadastrarProdutoActionPerformed

    private void btnAbrirMenuVisualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirMenuVisualizarProdutoActionPerformed
        VisualizarProdutoView view = new VisualizarProdutoView();
        view.setVisible(true);
    }//GEN-LAST:event_btnAbrirMenuVisualizarProdutoActionPerformed

    private void btnAbrirMenuDeletarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirMenuDeletarProdutoActionPerformed
        RemoverProdutoView view = new RemoverProdutoView();
        view.setVisible(true);
    }//GEN-LAST:event_btnAbrirMenuDeletarProdutoActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
       RelatorioView view = new RelatorioView();
       view.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnAbrirMenuAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirMenuAtualizarProdutoActionPerformed
        AtualizarProdutoView view = new AtualizarProdutoView();
        view.setVisible(true);
    }//GEN-LAST:event_btnAbrirMenuAtualizarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirMenuAtualizarProduto;
    private javax.swing.JButton btnAbrirMenuCadastrarProduto;
    private javax.swing.JButton btnAbrirMenuDeletarProduto;
    private javax.swing.JButton btnAbrirMenuVisualizarProduto;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
