/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.moonlight.moonlightapp.views.produtos;

import javax.swing.JOptionPane;

import com.moonlight.moonlightapp.daos.ProdutoProcessosDAO;
import com.moonlight.moonlightapp.models.ProdutoModel;

/**
 *
 * @author victor.santos8
 */
public class VisualizarProdutoProcessosView extends javax.swing.JFrame {
    private final ProdutoProcessosDAO produtoProcessosDAO;

    /**
     * Creates new form VisualizarProdutoProcessosView
     */
    public VisualizarProdutoProcessosView() {
        produtoProcessosDAO = new ProdutoProcessosDAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscarProcessosProduto = new javax.swing.JLabel();
        lblSelecionarProdutoProcesso = new javax.swing.JLabel();
        cbProdutoBuscaProcesso = new javax.swing.JComboBox<ProdutoModel>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutoProcessos = new javax.swing.JTable();
        btnBuscarProcessosProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuscarProcessosProduto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBuscarProcessosProduto.setText("Buscar Processos do Produto");

        lblSelecionarProdutoProcesso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSelecionarProdutoProcesso.setText("Selecione o Produto");

        cbProdutoBuscaProcesso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbProdutoBuscaProcesso.setModel(
                new javax.swing.DefaultComboBoxModel<>());

        tbProdutoProcessos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null }
                },
                new String[] {
                        "Nome", "Etapa", "Custo"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbProdutoProcessos);

        btnBuscarProcessosProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscarProcessosProduto.setText("Buscar");
        btnBuscarProcessosProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProcessosProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblSelecionarProdutoProcesso)
                                                                .addGap(46, 46, 46)
                                                                .addComponent(cbProdutoBuscaProcesso,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 216,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(50, 50, 50)
                                                                .addComponent(btnBuscarProcessosProduto))
                                                        .addComponent(lblBuscarProcessosProduto)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        1136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(14, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblBuscarProcessosProduto)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSelecionarProdutoProcesso)
                                        .addComponent(cbProdutoBuscaProcesso, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBuscarProcessosProduto))
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProcessosProdutoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarProcessosProdutoActionPerformed
        var produtoSelecionado = (ProdutoModel) cbProdutoBuscaProcesso.getSelectedItem();

        if (produtoSelecionado == null) {
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }

        var produtosProcessos = produtoProcessosDAO.buscarPorProdutoId(produtoSelecionado.getId());

        if (produtosProcessos == null || produtosProcessos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não há processos para este produto");
        }

        for (var p : produtosProcessos) {

        }
    }// GEN-LAST:event_btnBuscarProcessosProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarProdutoProcessosView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarProdutoProcessosView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarProdutoProcessosView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarProdutoProcessosView.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarProdutoProcessosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProcessosProduto;
    private javax.swing.JComboBox<ProdutoModel> cbProdutoBuscaProcesso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarProcessosProduto;
    private javax.swing.JLabel lblSelecionarProdutoProcesso;
    private javax.swing.JTable tbProdutoProcessos;
    // End of variables declaration//GEN-END:variables
}
