/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.moonlight.moonlightapp.views.principal;

import com.moonlight.moonlightapp.services.produtos.DeletarProdutoService;
import com.moonlight.moonlightapp.views.materiaprimas.CriarMateriaPrimaView;
import com.moonlight.moonlightapp.views.processos.AtualizarProcessoView;
import com.moonlight.moonlightapp.views.processos.BuscarProcessoView;
import com.moonlight.moonlightapp.views.processos.CriarProcessoView;
import com.moonlight.moonlightapp.views.processos.RemoverProcessoView;
import com.moonlight.moonlightapp.views.produtos.AtualizarProdutoItensView;
import com.moonlight.moonlightapp.views.produtos.AtualizarProdutoProcessosView;
import com.moonlight.moonlightapp.views.produtos.AtualizarProdutoView;
import com.moonlight.moonlightapp.views.produtos.CriarProdutoView;
import com.moonlight.moonlightapp.views.produtos.RemoverProdutoView;
import com.moonlight.moonlightapp.views.produtos.VisualizarProdutoItensView;
import com.moonlight.moonlightapp.views.produtos.VisualizarProdutoProcessosView;
import com.moonlight.moonlightapp.views.produtos.VisualizarProdutoView;
import com.moonlight.moonlightapp.views.relatorios.RelatorioView;
import com.moonlight.moonlightapp.views.tipos.VisualizarTiposView;
import com.moonlight.moonlightapp.views.unidadesmedidas.VisualizarUnidadesMedidasView;

/**
 *
 * @author victor.santos8
 */
public class MenuPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalView
     */
    public MenuPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMoonlight = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        lblDicaMenuSuperior = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnAdicionarProduto = new javax.swing.JMenuItem();
        mnRemoverProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnAtualizarProduto = new javax.swing.JMenuItem();
        mnAtualizarProcessos = new javax.swing.JMenuItem();
        mnAtualizarMateriasPrimas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnVisualizarProdutos = new javax.swing.JMenuItem();
        mnVisualizarProcessos = new javax.swing.JMenuItem();
        mnVisualizarMateriasPrimas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MnCriarMateriaPrima = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnCriarProcesso = new javax.swing.JMenuItem();
        mnRemoverProcesso = new javax.swing.JMenuItem();
        mnAtualizarProcesso = new javax.swing.JMenuItem();
        mnConsultarProcesso = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        mnConsultaRelatorio = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnConsultarTipos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnConsultarUnidadesMedidas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moonlight");

        lblMoonlight.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblMoonlight.setText("Moonlight");

        lblBemVindo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblBemVindo.setText("Bem Vindo(a)");

        lblDicaMenuSuperior.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblDicaMenuSuperior.setText("Acesse o menu superior para ver as funcionalidades");

        jMenu1.setText("Produto");

        mnAdicionarProduto.setText("Adicionar");
        mnAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAdicionarProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(mnAdicionarProduto);

        mnRemoverProduto.setText("Remover");
        mnRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRemoverProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(mnRemoverProduto);
        jMenu1.add(jSeparator1);

        mnAtualizarProduto.setText("Atualizar Informações");
        mnAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtualizarProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(mnAtualizarProduto);

        mnAtualizarProcessos.setText("Atualizar Processos");
        mnAtualizarProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtualizarProcessosActionPerformed(evt);
            }
        });
        jMenu1.add(mnAtualizarProcessos);

        mnAtualizarMateriasPrimas.setText("Atualizar Matérias Primas");
        mnAtualizarMateriasPrimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtualizarMateriasPrimasActionPerformed(evt);
            }
        });
        jMenu1.add(mnAtualizarMateriasPrimas);
        jMenu1.add(jSeparator2);

        mnVisualizarProdutos.setText("Visualizar Informações");
        mnVisualizarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVisualizarProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(mnVisualizarProdutos);

        mnVisualizarProcessos.setText("Visualizar Processos");
        mnVisualizarProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVisualizarProcessosActionPerformed(evt);
            }
        });
        jMenu1.add(mnVisualizarProcessos);

        mnVisualizarMateriasPrimas.setText("Visualizar Matérias Primas");
        mnVisualizarMateriasPrimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVisualizarMateriasPrimasActionPerformed(evt);
            }
        });
        jMenu1.add(mnVisualizarMateriasPrimas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Matéria Prima");

        MnCriarMateriaPrima.setText("Criar");
        MnCriarMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCriarMateriaPrimaActionPerformed(evt);
            }
        });
        jMenu2.add(MnCriarMateriaPrima);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Processos");

        mnCriarProcesso.setText("Criar");
        mnCriarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCriarProcessoActionPerformed(evt);
            }
        });
        jMenu3.add(mnCriarProcesso);

        mnRemoverProcesso.setText("Remover");
        mnRemoverProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRemoverProcessoActionPerformed(evt);
            }
        });
        jMenu3.add(mnRemoverProcesso);

        mnAtualizarProcesso.setText("Atualizar");
        mnAtualizarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtualizarProcessoActionPerformed(evt);
            }
        });
        jMenu3.add(mnAtualizarProcesso);

        mnConsultarProcesso.setText("Consultar");
        mnConsultarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarProcessoActionPerformed(evt);
            }
        });
        jMenu3.add(mnConsultarProcesso);

        jMenuBar1.add(jMenu3);

        mnRelatorio.setText("Relatório");
        mnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRelatorioActionPerformed(evt);
            }
        });

        mnConsultaRelatorio.setText("Consultar");
        mnConsultaRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultaRelatorioActionPerformed(evt);
            }
        });
        mnRelatorio.add(mnConsultaRelatorio);

        jMenuBar1.add(mnRelatorio);

        jMenu5.setText("Tipos");

        mnConsultarTipos.setText("Consultar");
        mnConsultarTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarTiposActionPerformed(evt);
            }
        });
        jMenu5.add(mnConsultarTipos);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Unidades Medidas");

        mnConsultarUnidadesMedidas.setText("Consultar");
        mnConsultarUnidadesMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarUnidadesMedidasActionPerformed(evt);
            }
        });
        jMenu6.add(mnConsultarUnidadesMedidas);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lblMoonlight)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(lblDicaMenuSuperior)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(lblBemVindo)
                .addGap(18, 18, 18)
                .addComponent(lblMoonlight)
                .addGap(18, 18, 18)
                .addComponent(lblDicaMenuSuperior)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelatorioActionPerformed
       RelatorioView view = new RelatorioView();
       view.setVisible(true);
    }//GEN-LAST:event_mnRelatorioActionPerformed

    private void mnConsultarTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarTiposActionPerformed
        VisualizarTiposView view = new VisualizarTiposView();
        view.setVisible(true);
    }//GEN-LAST:event_mnConsultarTiposActionPerformed

    private void mnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAdicionarProdutoActionPerformed
        CriarProdutoView view = new CriarProdutoView();
        view.setVisible(true);
    }//GEN-LAST:event_mnAdicionarProdutoActionPerformed

    private void mnVisualizarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVisualizarProdutosActionPerformed
        VisualizarProdutoView view = new VisualizarProdutoView();
        view.setVisible(true);
    }//GEN-LAST:event_mnVisualizarProdutosActionPerformed

    private void mnAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtualizarProdutoActionPerformed
        AtualizarProdutoView view = new AtualizarProdutoView();
        view.setVisible(true);
    }//GEN-LAST:event_mnAtualizarProdutoActionPerformed

    private void mnRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRemoverProdutoActionPerformed
        RemoverProdutoView view = new RemoverProdutoView();
        view.setVisible(true);
    }//GEN-LAST:event_mnRemoverProdutoActionPerformed

    private void mnAtualizarProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtualizarProcessosActionPerformed
        AtualizarProdutoProcessosView view = new AtualizarProdutoProcessosView();
        view.setVisible(true);
    }//GEN-LAST:event_mnAtualizarProcessosActionPerformed

    private void mnAtualizarMateriasPrimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtualizarMateriasPrimasActionPerformed
        AtualizarProdutoItensView view = new AtualizarProdutoItensView();
        view.setVisible(true);
    }//GEN-LAST:event_mnAtualizarMateriasPrimasActionPerformed

    private void mnConsultaRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultaRelatorioActionPerformed
        RelatorioView view = new RelatorioView();
        view.setVisible(true);
    }//GEN-LAST:event_mnConsultaRelatorioActionPerformed

    private void mnVisualizarProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVisualizarProcessosActionPerformed
        VisualizarProdutoProcessosView view = new VisualizarProdutoProcessosView();
        view.setVisible(true);
    }//GEN-LAST:event_mnVisualizarProcessosActionPerformed

    private void mnVisualizarMateriasPrimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVisualizarMateriasPrimasActionPerformed
        VisualizarProdutoItensView view = new VisualizarProdutoItensView();
        view.setVisible(true);
    }//GEN-LAST:event_mnVisualizarMateriasPrimasActionPerformed

    private void mnConsultarUnidadesMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarUnidadesMedidasActionPerformed
        VisualizarUnidadesMedidasView view = new VisualizarUnidadesMedidasView();
        view.setVisible(true);
    }//GEN-LAST:event_mnConsultarUnidadesMedidasActionPerformed

    private void MnCriarMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCriarMateriaPrimaActionPerformed
       CriarMateriaPrimaView view = new CriarMateriaPrimaView();
       view.setVisible(true);
    }//GEN-LAST:event_MnCriarMateriaPrimaActionPerformed

    private void mnRemoverProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRemoverProcessoActionPerformed
        RemoverProcessoView view = new RemoverProcessoView();
        view.setVisible(true);
    }//GEN-LAST:event_mnRemoverProcessoActionPerformed

    private void mnCriarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCriarProcessoActionPerformed
        CriarProcessoView view = new CriarProcessoView();
        view.setVisible(true);
    }//GEN-LAST:event_mnCriarProcessoActionPerformed

    private void mnConsultarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarProcessoActionPerformed
        BuscarProcessoView view = new BuscarProcessoView();
        view.setVisible(true);
    }//GEN-LAST:event_mnConsultarProcessoActionPerformed

    private void mnAtualizarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtualizarProcessoActionPerformed
        AtualizarProcessoView view = new AtualizarProcessoView();
        view.setVisible(true);
    }//GEN-LAST:event_mnAtualizarProcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnCriarMateriaPrima;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblDicaMenuSuperior;
    private javax.swing.JLabel lblMoonlight;
    private javax.swing.JMenuItem mnAdicionarProduto;
    private javax.swing.JMenuItem mnAtualizarMateriasPrimas;
    private javax.swing.JMenuItem mnAtualizarProcesso;
    private javax.swing.JMenuItem mnAtualizarProcessos;
    private javax.swing.JMenuItem mnAtualizarProduto;
    private javax.swing.JMenuItem mnConsultaRelatorio;
    private javax.swing.JMenuItem mnConsultarProcesso;
    private javax.swing.JMenuItem mnConsultarTipos;
    private javax.swing.JMenuItem mnConsultarUnidadesMedidas;
    private javax.swing.JMenuItem mnCriarProcesso;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenuItem mnRemoverProcesso;
    private javax.swing.JMenuItem mnRemoverProduto;
    private javax.swing.JMenuItem mnVisualizarMateriasPrimas;
    private javax.swing.JMenuItem mnVisualizarProcessos;
    private javax.swing.JMenuItem mnVisualizarProdutos;
    // End of variables declaration//GEN-END:variables
}
